FGGDKNBBB80DDGBBBBBHFFDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEBEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFHHFBFZ7QBEELHDN3BGBB73BBE266
FGGDKNBBBHHBBFFF999D8BBBBHBUD*BBFFDB4IYDDHFGDDEJBBBGNBBIGF*IDFLHDJN26FGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE26
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 6970: invalid continuation byte
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBEEBBBBBEHHBMBGB555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555533*EFE4DHJEEEFEEFGDDEG*BIYHDJNDJN3MBIBIBFJ*DB3GGDEBBBBBBHHBHBBDBGBBK3FFDBDGDDGFMBBJNMJ*33FGGDKNBDBEB9DFHBFDBDDBTF4DBBI4DHDDIYDDHBDMBBBGDDDBBHBDEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFBBBBNBBBBFFBBBBB*BDBBBBBBTBF4DDDBBBNBMGBHXDXEEEB9*EBEEEE999999EEEEG****EEEEEEEEEBEEEEEEEEEEEEG8GGGDID4HDDBGGBFGF3B5555555555555555E5555555555555555555555L555B55H5555B5BD55E5N5555555FG5G5D55K5N5BH55G5*5555555555B5B55555B5B55555595D555G5D5D5BG5553FD*FBDDB5BMIIBJ*DD3BB2E62MBGB26NBBB
FGGDKN80DDGBBBBHBDJN6
FGGDKNBBBBBHEEBBFEEEEEFDEB3B3BBB3BBB3B33EBFFF99BBB9DEEEEEEHHBF*4DBBGDDEBEFBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHW8GBNN*EBLHDJBJJ***D26FGGDKNBBBBB3B3BE80DDGBBBBBHFFBDJN

Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 3366: invalid continuation byte
FGGDKNBBGBBBBFFF999DBHHBHBBB99BBBFFDDDTFBD4DE*FBB9GBB9IGDDBBFFBE9F***TTTT99999999TTT*******N*3FBBBBF8BBBHZ7Q*EFBBBBBB99DIYGBYDB3G****9*F9999F**GFIGGTTBE*FGGDKNBDBEB9DFHBFDBDDBTF4DBBI4DHDDIYDDHBDMBBBGDDDBBHB8EBDEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDXXXXXXXXXXEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEGGGGDBID4HDDGGFGF3EBBBBBEEEEDDBBB26
FGGDKN8B**BBFFFBBHBBBFBBDBFDBBBBBDD*TFB4DGDDGFNBBHBBBBBBBBBBBBBBLHJBJJJJJJN23*B6NIGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFKBBBFFGGDFBHNBBBBBBBBBDFFF4DLHDJN2MBGB
GGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGBFIFHHFBFZ7QEELBHDN3BGBB7B3BB26D6FGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE26
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*BBB3GDBEBHFEEFEEBFFDEBEDDEEBIEEB80GB262MBGB
FGGDKN8EHHBBBEB9DEEEEEEEBBF*4DBBBBBBHGDDDEBBEFBBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN3HWNN*EEEBLHDJBJJ***D26FKBBBFFGGDNBBBEBHGDDGFBDFDHWF4BBDBDNBBFFHTID46*2*6FKBBBFFGGDNBBBBBBHBBBFBBDDFLHDJNFF4
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBEB80GB262MBGB
FGGDKNBBBFBHBFDBDDTFBD4D*YFGDDDFBBBBG*B***E****9
4DDDEBBBHDDDDBBBGGDBBDHBMGBBIBXDXEEEEBBEEEEEEEEEEEEEEEEEEEEEG8DGGGDNNMBID4HDDBBBDGGFFGFKB3IFHDHFBFZ7QEBELHDN3BG4B7B3HBBB26FGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE26
FGGDKNB80DDGBBBFBBBHFFDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EBDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFBEBBBDDBB266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
DBEBBBB9DFHBFDBBDDTFGGD4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDKEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFHHFBBFZ7QEELHDN3BGBB7B3BBFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE26
FGGDKNB80DDGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFBEBBEDDBBB266
FGGDKN*B80DDGBBBBBHDJNFGGDKNBBDBBBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGXDEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFIFHHFFZ7QBEELHDN3BGBB7B3B266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNBBBB*GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 1959: invalid continuation byte
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNBBBB*GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBBBBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKN80DDGBBBBBBHFFDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFHHFFZ7QEELBHDN3BGBB73BE2B66
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 6125: invalid continuation byte
FGGDKNBBBBB3B33B3BB3B3FHBHHBFFF999DB8DGBBBBBUD*BBFB4IYDDHFGDDEBJGNBBIGF*IDFLHDJN26FKBBBFFGGDNBBBBBHBBBBBDDFFFFLH4DJNFKBBBFFGGDBHFFDB4NEBDGDDGFDHWBNDBBHFFBT*2*6BLDJN
FGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFHHFBFBZ7QEELHDN3BGB73B26FGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE26
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJN2MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBEEEEB80GB262MBGB
FKBBBFFGGDNBBBEBHGDDGFBDFFD4DHWBBNDBBBFFHT*2*6
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*BBB3GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
8QYIBY5555IY555IIIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IYIY555IIY555IY555IY555IIIIIY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIIIY55533HFBDBEMBGBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII555IY555FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJN2MBGB
FGGDKN*HHFFBGDDBGBDBBIB3F8B3FFDB333*3B3BFFF99BB9DBF*4DBBBBBBBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHWNN*BLMBGBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIY5555IY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IYIY555IY555IY555IY555IIIIIY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIIY555I3HDEJN26
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNBTBFBHFDBDDBFBD4DBB*BYFGDDDFBBG*B***E**B
FGGDKNB80DDGBBBBBBHBDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGXDEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFHHFBFZ7QEELHDN3BGBB7B3BBEEEEE266
FGGDKNHBBBB999BBBBFFDDDBTFBD4DE*FBB9GB9DIGDDBBFFBE980GBBBBBBBBYDF
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 2553: invalid continuation byte
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 1773: invalid continuation byte
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBEEB80GB262MBGB
GGDDD2BGGD6FGGDKN80DDGBBBBBBHFFDJNFKNBBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGXDEEEEEEEEEEEEEEEGDGDID4HDDBGGFGBFIFBHHFBFZ7QBEELHDN3BGBB73BBEB6
DBDDLDJNFGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJN2MBGBFGGDKN3B80DDGBBBBBHDJN
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBBBBEBHFEEFEEBFFDEBEDDEEBIE80GBE262MBGB
FGGDKNBBBBBB33B3BB3B3FHBHHBFFF999DB8DGBBBBBUD*BBFB4BIYDDHFGDDEJGNBBIGF*ID
FGGDKNEBBBBBB80DDGBBBBBHDJNFGGDKNBBDBBBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGBGFGFEBBDDB266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 2894: invalid continuation byte
FGGDKNB80DDGBBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEEEEEGDGGGDBID4HDDGGFGFBIFHHFFZ7QEEBLHDN3BGB7B3BBE266
FGGDKNBBBBBBHBFBFDB3B3B3BB3B33HHBBFFF99BB9D8GBBBBBBUBETFD*4DIYDBHFGDDEJGNBBIGF*IDFLHDJN26FGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE26
FGGDKNBBF*B3LBH**9DJN3FHBEBFDDDJNBYFGDDDBBFBBJN*BJNJNJNJNJNJNJNJNJNJNJNJNJNJNBJNJNJNJNJNJNJN
FGGDKNBBBBHHBFH*D*MBGB***************************************************I*************************************************3BBB80DGBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFBEBBBEEDDBBB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB

FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBEEEEB80GB262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJN2MBGB
BHHDBBBF*HGBFBFDBDGDDGFGKBFGGDKNBGDBEHBFFBFFDBDDBLBHDBEBBJJJNBFF4DBBBBBBBBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN3HW8GBNN*MBGBIIIIIIIIIIIIIIIIIIBIIIIIIIIIIIIIIIIIIIIIIIIIIIY5555IY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IYIY555IY555IY555IY555IIIIIY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IIY5553NBFGFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBEBBBBBE3DIHBZ7QMBGB55555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555533*EFE4DHJIEFEEEFEEFGDDEG*IYHDBJNDJN3MBIBIBFJ*D3JNMJBB*BBBBB3GGDHB2BDEBGB62MBBGB3FGGDKNBDBEB9DF
FKBBBFFGGDNBBBEBHGDDGFDBFFD4DHWBBNBDBBBHFFBT*2*6
FGGDKNBB80DDGBBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EBDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGBFEBBBDDBB266
FGGDKNBDHBFFDBBBBBBBDD*TFB4DGDDGFNBBHEBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB8BLHJBJJJJJNHHFGIFHZ7QBBB****BBBB3B*26NBB999BE*FBB9B9DFBE9F***TTTT99999999TTT*******N*3**BB*E****FBBBBB99DIYYDBG****9*F9999F***GFI3GGTT*FGGDKNBDBEB9DFHBFDBDDBTF4DBBI4DHDDIYDDHBDMBBBGDDDBBHB8EBDEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDXXXXXXXXXXXEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEGGGGDID4HDDBGGFGFB3EBBEEEEDDB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNB80DDGBBBBFBBHFFBDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEGDGGGDID4HDDGBGFGFBIFHHFBFBZ7QEELHDN3BGB7B3B266
FGGDKNBB80DDGBBBBBHFFDJNFGGDKNBBDBBBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EBDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDGBGFGFIFHHFBFZ7QEBELHDN3BGB7B3BBBE266
BDIBBDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBD4DEHDDDDBBGGDBDHMGBXDEEEEEEBBEEEEEEEEEEEG8DGGGDNMBID4HDDDBGGFFGFKB3IFHDHFBBFZ7QBEELHDN3BG4BB7B3HB26D6FGGDKN83BD0DDGBBBBHBDJN
FKBBBFFGGDNBBBHFEFBBGDDGFDD4HWDBBNDBBBHFFT*2*6FKFBBHBBFFGGDNBBBD3FFFD4D26


FGGDKNB80DDGBBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFEBBBDDBB266
HG4BDFFGBFGGDK3I8FGHDHFBBBBFBZ7QEBELHDN3BG4BB7B3BHBDBBBBDMGBBIBXDDBBEGHDGGGDDNB26D6FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJN2MBGB
FGGDKNB80DDGBBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGBFEBBBEDDBB266
FGGDKNB80DDGBBBBFBBHFFDBJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGXDEEEEEEEEEEEEEEEEEGDGGGDID4HDDBBGGFGFBIFHHFFZ7QEELHDN3BGB7B3BB266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNB80DDGBBBBFBBHFFBDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBBBDDBBB2B66
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 1958: invalid continuation byte
FGGDKNFB80DDGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGXDEEEEEEEEEEEEEEEEEEGDGGGDID4HDDBGGBFGFIFHHFFZ7QEBELHDN3BGBB73B2B66
FGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBEEB80GB26
FKBBBFFGGDNBBBEBHFBBGFDDD3GFD4HWDBDNBBHFFT*2*6FGGDKNBBBFHBHHBBBFFF999D8BBBBBB0DGBBFETFD4UD*BIYDHFGDDEBJGNBBIGF*IDFLHDJN26
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJN2MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBBBBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNBBFBBBDBHBDDFFBTFB4DBDG9DIGDDBBGFBBT*EFBBBB*BBB99DF99999F*BBBHENIYBBFJFBH*HH**GFIYGGTTBE*EB*****BI*F*FDBBNF**BGBBBBEB**BBDBG****E3***3E99FF99BBBBBB*HFB8Z7QB***FMGB
FGGDKNB80DDGBBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFBEBBBEDDBBB266
FGGDKNHB80DDGBBBBBBHDJN6FGGDKNBBBBBB3BB3
FGGDKNBBBBHHBBFH*D*MBGB***************************************************I************************************************3BBB80DGBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFEBBEEDD266
FGGDKNBDHBFBFDBBBBBBDD*TFB4DGDDGFNBBHBBBBBBBBBB3BEBJHIGF*IDFLDJ8Z7*3QNFKBBBFFGGDNBBBBBHBBBBBDDFFFBHBBFBLHDJN4FKFBHBBFFGGDNBBBBE26B26IYLHDEJN**3B*2
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJN2MBGB
*3B33BBFFF99BBB9DBF*4DBBBBDGGDBBFBBKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN3HW8GBNN*BLBMBGBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIY5555IY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IYIY555IY555IY555IY555IIIIIY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIIY555IIY5553HDEJN2FGGD6KNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBBBBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 2532: invalid continuation byte
BGBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIBY5555IY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IYIY555IY555IY555IY555IIIIIY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIIY555IIY5553MFGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJN3B2MBGB
FGGDKNBBBBHHBBFH*D*MBGB***************************************************I*************************************************3BBB80DGBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGXDEEEEEEEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFBEBBBEEDDBBB266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNBBBB*GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNB80DDGBBBFBBHFFBDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFBEBBBDDBB2BB66
FGGDKNBF8TGFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGBFIFHHFBFZ7QEBELHDN3BGBB7B3BB2B6
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 2146: invalid continuation byte
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNHBFFDBBBB80DGBBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEEEBEEEEGDGGGDID4HDDGGFGFBEBBDDBB266
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 2552: invalid continuation byte
FGGDKNBBBBB3B33B3HBB3B3BFFF999DFBBHHBBF*4DBBBBGDDDBFBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHW8GBNN*MFBGGGDKNBB*LGBDBIEIIIIIBHIIFIIEIIIEIIIIIIIIIIFIIIIIIIIIIIIIIIIIIIIIIY5555IY555IY5E55IIY555IEY555IY555IIIIY555IY555IY555IY555IYB555IFY555IY555IY555IY555IY555IY555IY555IIYF5D5E5IY555IY555IY555IY5B55IEY555IY555IY555IY555IY555DIDY555IY555IEYIY555IEY555IY555BIY555IIIIIEIYB555IBY80555GIBIYE555IY555IY555IY555IY555IY555IY555IY5525IY6555IY555IIIY555IHDEJN26
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBEB80GB262MBGB
FGGDKNBBBBHHBFH*D*MBGB***************************************************I**********************************************3BBB80DGBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBMGBXDEEEEEEEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBEEDDBB266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*B3BBGDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNB80DDGBBBBFBBHFFBDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFBIFHHFBFZ7QEELHDN3BGBB7B3BB2B66
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBBBBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 2145: invalid continuation byte
FGGDKNBBBBFFBFHBHHF*D*MBGB***************************************************I*************************************************3BBB80DGBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGXDEEEEEEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFBBBHHFFZ7QBEELHDN3BGB73BEE266
FGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFHHFFZ7QEEBLHDN3BGBB7BNBI4DHDDDDHNDMBDDDHBBBBBBBBBBBBBBBBBDBMXDEDDBBBBNBB3BBE26
FGGDKNBBB3BB3
FGGDKNB80DDGBBBBBHBDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFHHFFZ7QEBELHDN3BGBB7B3B266

D6FGGDKN26
FGGDKNBB80DDGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFIFHHFBFZ7QEELHDN3BGBB73BBEEE266
FGGDKNBBGBBFBBFBFFF999DFHBBHHBBB99BBBFDDDTFBD4DE*FBB9GB9IGDDBBFFBE9B80GBBBBBBBBYDFBG****
FGGDKNHB*FBBBBBBB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBBBBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNBBB3B33BBBBB3B33BBBHHBF*HBFBDBDGDDGFFGGDKNBGDBEHBFFBFFDBDDIYBB9DGDDFBFBBFBFBB4DBBBBBBBBBXXXBXX
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJN2MBGB
FGGDKNBBBBB3B3BE80DDGBBBBBHFF
GGDKNBBBBB3BB33B333BB3B3EFFF999DEFEEEEHBBEEEEEEHHBBF*4DBBBBGDDDEBEFBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHW8GBNN*EEEBLHDJBJJ***D26FGGDKNBBBBB*HHFFGDDBBGDBBIB3F8B333FFDB333*3B3BFFF99BB9DBF*4DBBBBBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHWGBNN*BMBGBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIY5555IY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IYIY555IY555IY555IY555IIIIIY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555ILHDEJN26FKBBBFFGGDNBBBBBFHBBBBDDFFBHBBBBBBBBBBBBBBBBB26
FGGDKNBBBBFHBHHBBB9D8BBBBBBU0DGBFED*TF4BDIYBDHFGDDEJGNBBIGF*IDFLHDJN26FKBBBFFGGDNBBBBBBHBBBBBDDFFLHDJNFF4LBDJN
GGDKNBGDBEHBFFBFFDBDDIYBB9DGDDFBFBGGDBBBHFFFBB4DBB*BBBBDBBBKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN3HW8GBNN*MBGBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIBIY5555IY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IYIY555IY555IY555IY555IIIIIY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IIY5553NBHFGDIGDDHFBBQ3EFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGXDEEEBEEEEEEEEEEEGDGGGDID4HDDGGFGFBIFHHFBFZ7QEBELHDN3BGB73BBB26
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJN2MBGB
FGGDKNB80DDGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGXDEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFBIFHHFBBFZ7QEELBHDN3BG73BB266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBEB80GB262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNB80DDGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGBFGFIFHHFFZ7QEBELHDN3BGBB7B3BBEB266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GBBBDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNFFFFFFFFFFBFBBFHGDD*H*UUFBBLBHBDEJN*LDJN2B6
BBB9DHHDBBF*B4DBBBBBBBGHGDDDGFBBBBKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN3HW8NN*MBGBIIIIIIIIIBLIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIY5IY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IYIY555IY555IY555IY555IIIIIY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555I3HDEJN2B6FGGDKN8EEEEEBBEB9DEEEEEEEHHBBFB*4DBBBBBBHGDDDEEFBBBBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN3HWNN*EEEBL3HDJBJJ***D26FGGDKNBBB3BBB3BBB3B3FFBFBFFF999DFHBBHHBF*BFDBDGDDGFB
FGGDKNBBBBFHBHHBBB9D8BBBBBBU0DGBFBDET*B4FDIYDBHFGDDEJGNBBIGF*IDFLHDJN26FKBBBFFGGDNBBBBFBBBBHBBDDFLHBDJNFF4FGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHLWDJWN3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGXDEEEEEEEEEEEEEEEGDGGGDID4HDDGBGFGFIFBHHFBFZ7QBEELHDN3BGBB73BBB26
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJN2MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBEB80GB262MBGB
FGGDKNBHBBBB999BBBBFFDDDTFBD4DE*9E9BB**BBBBBYFGDDDFBG*BB***999999****
FGGDKNB80DDGBBBFBBBHFFDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EBDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEGDGGGDID4HDDBBGGFGFIFHHFBBFZ7QEELHDN3BGB7B3B266
FGGDKNB80DDGBBBBBBHFFBDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEGDGGGDID4HDDGBGFGFBEBBBDDBBB2B66
FGGDKNHBFFDBBBB80DGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGBFBEBBBBDDBB266
FGGDKN8BBEEFFEB9DEFEEEEHBEEEEBBFB*4DBBBBBBGDDDEEFBBBBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE26
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 2551: invalid continuation byte
FGGDKNB80DDGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFBBEBBBDDBBB266
FGGDKNE33BBB3HBFFBBFFDBB3B333HHBBFFF99BB9D8BBBBUDB*4IYDDHFGDDEJBGNBBIGF*IDFLHDJN26FGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE26
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*B3BBGDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
BHHDBBFBFF999D8BBBGGBHUBBD*KBBFFDB4IYDDHFGDDBEJBGNBBIGF*IDFGGDKNB*GDBFELHDJNB2H6FEEFEEBFFDEBEDDEEBIEBB80GBE26
FGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFHHFBBFZ7QEELHDN3BGBBB73BBB26
FGGDKNBBB80DDGBBBBBHFFDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFBEBBBEDDBB266
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 2553: invalid continuation byte
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNBBBB*GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNB80DDGBBBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFHHFFZ7QEBELHDN3BGB73BEE266
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 2139: invalid continuation byte
FGGDKNLBBFBHFFBDJNFHBFD4IYDDBBBHFGDDDEJGNBBIGF*IDFLDJNFKBBBFFGGDNBBBBBFBBBHBBDDFFBFL4HDJNFKBFBHBBFFGGBDNFBBDFEBHWWFGDD8E426FKFBHBBFFGGDNBBBBE26B26
FGGDKNB80DDGBBBFBBBHFFDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGXDEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGBFIFHHFBFZ7QEBELHDN3BG7B3B266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*BBB3GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 7364: invalid continuation byte
FGGDKNB80DDGBBBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFHHFBFZ7QBEELHDN3BG7B3BB266
FGGDKN8FBBFBBBB9DHHBF*B4DBBBBBBHGDDDFBBBBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN3HWNN*MBB3LGBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIY5IY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IYIY555IY555IY555IY555IIIIIY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IIY5553HDEJN2BB6FGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EBDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFBIBFHHFBBFZ7QEELHDN3BGB7B3BB26
FGGDKNBB80DDGBBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFHHFFZ7QEELHDN3BGBB7B3BB266
FGGDKNBGDBEHBFFBFFDBDDIYBB9DGDDFBFBGGDBBHBFFFBB4DBB*BBBBDBBBKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN3HW8GBNN*MBGBIIIIIIIIIIIIIIIIIIIIIBIIIIIIIIIIIIIIIIIIIIIIIIY5555IY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IYIY555IY555IY555IY555IIIIIY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIIY555IIY5553NBHFGBBDIGDDHBQBFE3FGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE26
FGGDKNBBB
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 1958: invalid continuation byte

EBDKGGDEBD4DBDDHDDBBHDDHWW3HH8BIBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBEBDDDBBBMGXDEEEEEEBBEEEEEEEEEEEGDGGGDNMBID4HDDDGGFFGFIFHDHFFZ7QEELHDN3BG473B26D6FGGDKN83BD0DDGBBBBHDJN
FGGDKNBFHBB80DDGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEBEEEEEGDGGGDID4HDDGGFGFEBBDDB266
FGGDKNBBBBB3B33B3BB3B3BFFF999DFHBBHHF*4DBBBBGDDDBFBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHW8GBNN*MBGBIIIIIIIIIIIBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIY5BIY555IY555IIY555IY555IY555IIIIY5
FGGDKNBDHBFBFDBBBBBBDD*TFB4DGDDGFNBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNBB80DDGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBBBBDDBB266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNEBBBBBBBBDBLBBHDEJN26FGGDKNB*GDBEHEEFEEBBBFBBEEBBBBBHDJN26
FGGDKNBX*80DDGBBBFBBHFFDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFIBFHHF
FGGDKN8BBEEFFEB9DEFEEEEHBEEEEBBFB*4DBBBBBBGDDDEEBFBBBBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN3HWNN*EEEBLHDJBJJ***D26FGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE26
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNBBBB*GDBEBHFEEFEEBFFDEBEDDEEBIEEEBBBBBEHHBMBGB55555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555533*EFE4DHJEEEFEEFGDDEG*BIYHDJNDJN3MBIBIBFJ*DB3GGDEBBBBBBHHBHBBDBGBB3JNMJ*3KLFHDENFDBDGDDGFFGGDKNBDBEB9DFHBFDBDDBTF4DBBI4DHDDIYDDHBDMBBBGDDDBBHBDEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFBNBFFBB*BDBBBBBBBBTF4DDDBBBNBMGBHXDXEB9*EBEEEE99999E9EEGE****EEEEEEEEEEEEEEEEEEEEEEEG8GGGDID4HDDBGB555555G555555555F555G5555F5B555555555553555555555555555555555555555B55E5555555N355555555555B55555555555555BB5555555MIIBJ*DD32E62MBGBNBIY9DGDDFBFFBB3DDBB26FGGDKNBBHGDDDBBB*DIGBF3BFB9DBBNGFD3FBFFIYDTFHBBBBBB**HFGBDG*HF3Z7Q*U*HHDBJJJFINUHEFF9BZ7*BN*9F*BBBB9B*BTBBBBB9
FGGDKNB80DDGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBEDDBBB266
KFFBBHBBFFGGDNBBBFDF3FD4D26DBBBDBBBBBBBBDLDEJNBBBB2BGGD6
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
333HGEBFEFDEBB333*3B3EBFFF99BBB9DEEEBF*4DBBBBGDBBEFBBKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHW8GBNN*BLHDJBJJ***D26FGGDKNBBBBBBBB3BN3BB3B33HHBFFF999D8DGBBBBBBBBFHFEUD*TBF4BIYDDBHFGDDEJGNBBIGF*IDFLHDJN26
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNBB80DDGBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFIFHHFBFZ7QBEELHDN3BG73BB266
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 2512: invalid continuation byte
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNBBBB*GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJN2MBGB
FGGDKN80DDGBBBBBBHFFDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBBGDDDHWW3BBH8EDEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBBBDDBB2BB66
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJN2MBGB
HHFGGDDBDDEBJBDGGDKNBBBIGF*FGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EBDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFIFHHFFZ7QEBELHDN3BG7326
FGGDKNBBB3BBB3BBB3B3FFBFBFFF999DFHBBHHF*BFDDGDDGFBFGGDKNBGDBEHBFFBFFDBDDIYBB9DGDDFBFBBFBB4DBBBBBBBBBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHW8GBNN*MBGBBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIY5555IY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IYIY555IY555IY555IY555IIIIIY555IY555IIY555IY555IY555IY555
BBELHDN3BG4H8BBZ7FBB3BBBHDDBGKDBBGGBBDMGBBIBXDDBBGHDGGGDDN26FNBE9DFFDBDTFDI4DHDDIYDDHBNDMBGDDDHWW3BBEDEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBMXDEEEEEEEEEEEEEEEEEEEEEEEEEDDID4HDDGFGIFBHHFF7QBENBBBBEEB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*BBB3GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBBBBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKN80DDGBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBMGBXDEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFBHHFBFZ7QEBELHDN3BGB73BB266
FGGDKNB80DDGBBBBFBBHFFBDJNFKBBBFFGGDNBBBBBHBBBBFBDDFLHDJNFF4LDJN6
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNBBBBBB3BB33B333BB3B3BFFF999DFHBBHHBF*4DBBBBGDDDBFBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHW8GBNN*MBGBB3LBHDEJN26FGGDKNBBBBBB3BB33B333BB3B3EBFFF999DEFEEEEHBBEEEEEEHHBBF*4DBBBBGDDDEBEFBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHW8GBNN*EEEBLHDJBJJ***D26
FGGDKNBBBBHHBFH*D*MBGB***************************************************I**********************************************3BBB80DGBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFBEBBEEDDBBBB2B66
FGGDKN80DDGBBBBHDJN
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNBBBB*GDBEBHFEEFEEBFFDEBEDDEEBIEEEBFFFF999DEBBBBBEBMBGB555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555533*EFE4DHJEEEFEEFGDDEG*IYHDBJNDJN3MBIBIBJ*DB3BBEBBBBBGGDHBBDBGB3JNMJ*32E62MBGBFKNFFFBFDBD*BDBBBBBBBBBTF4DFGGDKNBGDDBDEGFBB9DFNHBFDBBDDBTFH4DBBB9*BI4D99999H9DDIYDGD*H**B*DMBBBGDDDBBHBDEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDXEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG8GGGDID4HDDBGGFGF3EBNBBBBDDBBB26
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIY5555IY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IYIY555IIY555IY555IY555IIIIIY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555II3HDJBJJ**8*D2GGD6FKBBBFFGGDNBBBBBBHBBBBBDDFFBHBBLHDJNFF4FKFBHBBFFGGDNBBBBFED26BB26
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNBBBB*GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBBBBBBEBMBGB555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555533*EFE4DHJEEEFEEFGDDEG*IYHDBJNDJN3MBIBIBFJ*DBBBB3BBBGGDHBBDBGBB3JNMJ*32E62MBGBKLFBHDEFDBDN3GDDGFBFNFF*BDBBBBBBBBTF4DNBHB9*B999999G****FGGDKNBDBEB9DFHBFDBDDBTF4DBBI4DHDDIYDDHBDMBBBGDDDBBHBDEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGXDXBEEEEEEEEEEEEENBEEEEEEEEEEEEEEEEEEEEG8GGGDID4HDDBGGFGF3IFHHFBBFZ7QENIYN9EDLHDN3GDDFBFFB3BGB7BB
FGGDKNBBB80DDGBBBBFBHFFDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGXDEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFHHFBFZ7QEELHDN3BGB7B3BB266
555IY5555IY555IIYIIIY555IY555IY555IY555IIY555I3MBGBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIY555IY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IYIY555IY555IY555IY555IIIIIY555IY555IIY555IY555IY555IY555IY555IY5553BBFKBFBHBBFFGGDNBBBFEBHWWFGDD8E26FGGDKN8BBBFFB9DFHBBFB*4DBBBBBBBGDDDFBBBBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN3HWNN*MBGBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIBIIIIY5BIY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555
FGGDKNBBBBHHBBFH*D*MBGB***************************************************I*************************************************3BBB80DGBBBBHDJNFGGDKNBBBBBBB33B3HBB3B3EEEFBFEBFFF999DEEEEEEEEHHBF*4DBBBBBGDDBDEBEFBBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHW8GBNN*EEEBLHDJBJJ***D26
FGGDKNBB80DDGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEGDGGGDID4HDDGGFGBFBEBBBBDDBBB266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIBEE262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNBBBB*GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNBBFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE26B
FGGDKN8B**BBDHBFBFDBBBBBBDD*TFB4DGDDGFNBBHEBBBBBBBBBBBB3BEBBJLHJBJJJJJJJNB**B*26NIGBBIYBJNF*IDFLDJNHLDEJNFKBBBFFGGDNBBBBBBHBBBBBDDFFFFBHB4BBBBBBBBBBBBBBBBBB2B6FGGDKN8B**BBDHEEBBFEEEEEBFDEBBBBBBEEDD*ETF4DGDDEGFNBBHBBBBBBBBBBBBB3BEBJLHBJBJJJJJJJNB**B*26
FGGDKNHBBBBBLBBHDDJBBBJJN26NBLDEJNFGGDKNHBBBEBBLBBHDJBBBJJN26NHGDDW
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBEEB80GB262MBGB

FGGDKNB80DDGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFHHFFBZ7QEELHDN3BGB73BEE266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNB80DDGBBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBBDDBB266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*B3BBGDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJN2MBGB
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 2416: invalid continuation byte
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 2625: invalid continuation byte
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB

FGGDKNB80DDGBBBBBBHFFDJN
FGGDKNHB80DDGBBBBFBBHFFDBJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBMGXDEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFHHFBFZ7QEBELHDN3BG7B3BB2B66
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNFFBBHBFBBBFDBF4IYDDHFGDDDEJBGNBBIGF*IDFLHDJNLDJNFKBBBFFGGDNBBBBBHBFBBBBDDFFLHDFJN4FKBFBHBBFFGGDNBBBFEBHWWFGDDF8DE26FKFBHBBFFGGDNBBBBFDE2626
FGGDKNBB80DDGBBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFIFHHFBBFZ7QEELHDN3BGB73B266
FGGDKNBBGBBBBFFF999DBHHBHBBB99BBBFFDDDTFBD4DE*FBB9GBB9IGDDBBFFBE9F***TTTT99999999TTT*******N3*FFHZ7Q8B*EBFBBBBBBB99DIYG3YD*F9999F**GFIGGTTBBEFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBDMBBGDDDBBHB8EBDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGXDXXXXXXXXXXEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEGGGGDBID4HDDGGFGF3BIFHHFFZ7QBEEBLHDN3BGBB73BBEEEEEEEEEEE26
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*BBB3GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNBBFB*L3BHD**9BEBJFN3HFDDDBYFGDDDBFBBBBGB*****ETFD4DBBBJNJNJNJNJNFKBBBFFH3GGDNBFEBFDB4BGDDDGFDNBHWBBHDFFBT*2*6JNBNBB3JNBNJNJNBNJNBJNNJNBNJNBNJNBN
FGGDKNBBBBHHBFH*D*MBGB***************************************************I************************************************3BBB80DGBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBEEDDBB266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNBB80DDGBBBBBHDJNFGGDKNBBDBBBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBEDDBBB266
FGGDKNBBBBHHBBFH*D*MBGB***************************************************I*************************************************3BBB80DGBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBEEDDBB2B66
FGGDKNHB80DDGBBBBBBHFFDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDBEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBDDBBB266
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 2602: invalid continuation byte
DBBDDLDJNFGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBEB80GB262MBGB
FGGDKNBBF*L**9FBHB3HBDJN3EBFDDDBYFGDDDBFJNBBBBGB*****JNBJNJNJNJNJNJNNJNJNJNJNJNJNJNBJNJNJNJNJNJNJNJNBJNJNJNJNJNJNJNJNJNJNFKJN
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 2145: invalid continuation byte
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*BBB3GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
BBB3HGBFFDB9D333*B3B33BFFF99BB9BF*4DBBBBGDBBFBK
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 2552: invalid continuation byte
FGGDKNBB80DDGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBEDDBB266
FGGDKNBBBBB*HHFFGDDBGBDBBIBF83B33
FGGDKNB80DDGBBBBBBHFFDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDGGBFGFBEBBBEDDBB266
FGGDKNBB80DDGBBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGXDEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFBIFHHFBFZ7QEELHDN3BGB73BEE266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*BBB3GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNB80DDGBBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBBDDBBB266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*B3BBGDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJ
FGGDKNBBBBHHBFH*D*MBGB***************************************************I*************************************************3BBB80DGBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFBEBBBEEDDBB266
FGGDKNB80DDGBBBFBBBHFFDJNFGGDKNBBDBBBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGXDEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFBIFBHHFBFZ7QEELBHDN3BGB7B3B266
FGGDKN80DDGBBBBBBHFFDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBBGDDDHWW3BBH8EDEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGXDEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGBFIFBHHFBFZ7QEELHDN3BGBBB73BBE2B66
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBBBBBBEBMBGB555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555533*EFE4DHJEEEFEEFGDDEG*BIYHDJNDJN3MBIBIBFJ*D3JNMJ*B32E62MBGBFGGDKNBBBBBHBFBFDBB3B33BBB3B3HHBBFFF99BB9D8GBBBBBBBEUTFD4*DBIYDHFGDDEJGNBBIGF*IDFLHDJN26
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 4236: invalid continuation byte
FKBBBFFGGDNEBBBBHFB3GDDGFDFD4DHWBNDBBBHFFT*2*6BN3BBNBN
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBBBBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNBBB3B33BBBBB3B33BBBHHBF*HBFBDBDGDDGFFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBEEHHBMBGB55555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555533*EFE4DHJEEEFEEFGDDEG*IYLHDBJNLDJN3BBFF4DBBBBBBBBBBXXXXXXXMBIBIBFJ*DB3BGGDHHBHBBDBGBB3JNMJ*3FGGDKNBDBEB9DFHBFDBDDBTF4DBBI4DHDDIYDDHBDMBBBGDDDBBHBDEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFKNFFFFDBD*BDBBBDBDBBBBBTFM4GDGDDGXDXFNEBEBEEEHEEEEEB9E*BEEEE999999EEEEG****EEEEEEEEEB5E555555E555555555555555E5555E5555555555E555555555555555555555555555555555555555555555555555555555555555553G8GGGDID4HDDGGFGF3IBFBBHHFFZ7QEELHDN3BGBB73BEE26
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNBDHBFBFDBBBBBBDD*TFB4DGDDGFNBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFB3*EJHIGF*IDLDJ8Z7*3QNFKBBBFFGGDNBBBBBHBBBFBBDDFFBFBHBBB3LHBDJN4FKFBHBBFFGGDNBBBBE26BBB26*LHDEJN**3*2F6
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNBBBB*GDBEBHFEEFEEBFFDEBEDDEEBIE80GBE262MBGB
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 2511: invalid continuation byte
BHHDDBGBKDBBGGBBDMGBBIBXDDBBEGH8DGGGDDNB26FGGDKN80DDGBBBBHDJN
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIBEEEB8E262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBBBBFFDEBEDDEEBIEEB80GB262MBGB
FGGDKNBBBBB*HHFFGDDBGBDBBIBF38B333FFDB333*3B3BFFF99BB9DF*4DBBBBBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHWGBNN*BMBGBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIY5555IY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IYIY555IY555IY555IY555IIIIIY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY55
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNBBBB*GDBEBHFEEFEEBFFDEBEDDEEBIEEEB80GB262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJN2MBGB
FKBBBFFGGDNBBBBBHBBBBBDDLFHFDJNFF4FKBBBFFGGDNBBBEBHGDDGFBDFDFHW4DBBDNBBFFHT*2*6LDJNFGGDKNBBBBBBB33B3HBB3B3FBBFBFFF999DHHBF*4DBBBBGDDDBFBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHW8GBNN*MBGBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIBIIIIIIIIIII
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNBBBBB3B3BE80DDGBBBBBHFFBDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGXDEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFHHFFZ7QEBELHDN3
FGGDKNBB26
FGGDKNB80DDGBBBFBBBHFFDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEGDGGGDBID4HDDGGFGFEBBDDBBB266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 1890: invalid continuation byte
FGGDKNBHB80DDGBBBFBBHFFDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEGDGGGDBID4HDDBGGBFGFBEBBBDDBB266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBEEBBBBBEHHBMBGB55555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555533*EFE4DHJEEEFEEFGDDEG*BIYHDJNDJN3MBIBIBFJ*DB3BGGDEBBBBBHHBHBBDBGBB3JNMJ*3BFGGDKNBDBEB9DFHBFDBDDBTF4DBBI4DHDDIYDDHBDMBBBGDDDBBHBDEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFBKBNBBFBFBBBFBFDBBBBBDBBBBB*BBBDBBBBBBBBBTF4DBGDDGFNDDBBBBMGHBXDBX9*BEEEEE999999EEEEG****EEEEEEEEEEEEEEEEEEEEEEEEB55555555555555555555555555555555555555555555555G8555555G5G5G5D5555555555555555555555555555555555555555555553ID4HDDBGGFGF3EBBBDDNBB526
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKN8BBEEFFEB9DEFEEEEHBEEEEBBFB*4DBBBBBBGDDDEEFBBBBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN3HWNN*EEEBL3HDJBJJ***D26FKBBBFFGGDNBBBEBHGDDGFBDFFD4BHWDBNDBBHFFBTID46*2*6FGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GBBBDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*BBB3GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNB80DDGBBBBFBBHFFDBJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDBEEEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFEBBDDBB266
FGGDKNB80DDGBBBBBBHFFDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEGDGGGDBID4HDDGGFGFEBBBDDBBB266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNBB80DDGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGBFEBBBDDBB266
FGGDKNBDHBFBFDBBBBBBDD*TFB4DGDDGFNBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
FGGDKNFFBBHBFBBBFDBF4IYDDHFGDDDEJBGNBBIGF*IDFLHDJNLDJNLJNFKBBBFFGGDNBBBBBFBNHBBBBBBBBFFDDBFLL3HDJNJ4NFKBFBHBBFFGGDNBBBFEBHWWFGDD8E26FKFBHBBBFFGGDNNBBBBE2626
FGGDKNBBBBBB3BB33B333BB3B3FHBHHBBFFF999D8DGBBBBBBBUBFETFD*4BDIYDHFGDDEBJGBBNBBIGF*IDFLHDJN26FKBBBFFGGDNBBBBBBHBBBBBDDFFLFFHDJN4LBDJNFKFBBHBBFFGGDNBBBFDF3BFD4D
FGGDKNBB80DDGBBBBBHDJNFKBBBFFGGDNBBBFBBHBBBBBDDFLFHDFJN46
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 2602: invalid continuation byte
FGGDKN80DDGBBBBBBHFFDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFEBBDDBB266
FKFBBHBBFFGGDNBBBDF3FFD34DFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE26
FGGDKNB80DDGBBBBBBHFFDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGXDEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFHHFFZ7QEBELHDN3BGBB7B3BE266
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 7588: invalid continuation byte
FGGDKNBDHBFFDBBBBBBBDD*TFB4DGDDGFNBBHBBBBBBBB3EBJHIGF*IDFLDJ8Z7*3QNFKBBBFFGGDNBBBBBHBBBBBDDFFFBHBBFBBL3HBDJN4FKFBHBBFFGGDNBBBBE26BB26IYBLHDEJN***3*26
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJN2MBGB
FGGDKN8BEFEEFEEEEEHBFBBEB9DEEEEEEEEHHBFB*4DBBBBBGDDDEEFBBBBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN3HWNN*EEEBLBHDJBJJ***D26FGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGXDEEEEEEEEEEEEEEGDGGGDID4HDDGBGFGFBIFHHFBFZ7QBEELHDN3BG7B3BBB26
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 4055: invalid continuation byte
FGGDKN80DDGBBBBBBHFFDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGXDEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFIFHHFBFZ7QBEELHDN3BGBBB73BBE266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBBBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNBB80DDGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBBBDDBB266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNBBFBB8B0DDGBBBFBBHFFBDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEGDGGGDID4HDDBGBGFGFIFHHFBFZ7QEELHDN3BG73BB266
FGGDKN6
32GGD6FGGDKNBBBBBB33B3BB3B3FHBHHBFFF999DB8DGBBBBBUD*BBFB4IYDDHFGDDEBJGNBBIGF*IDFLHDJN26FKBBBFFGGDNBBBBBHBBBBBDDFFLFFH4DJN
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJND62MBGB
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 1957: invalid continuation byte

FGGDKNBBBBBHBFBFDBB3B33BBB3B3HHBBFFF99BB9D8GBBBBBBBETFDU4D*IYDBHFGDDEJGNBBIGF*IDFLHDJN26FKBBBFFGGDNBBBBBHBBBBBDDFFFLHDJNF4
FGGDKNB80DDGBBBBBHBDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFBEBBBEDDB266
FGGDKNB80DDGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFBEBBBDDBB266
FGGDKNBBBBB3BB33B333BB3B3FHBHHBBFFF999D8DGBBBBBBBUBFED*TB4FIYDDHFBGDDEJGNBBIGFFG*GDKNB*GDBEIDBHFEFLEHDJN2F6EEBFFDEBEDDEEBIEBB80GBE26
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNDBDDLBDJNFKFBBHBBFFGGDBFNFDFD34DBBBBBBBBGGDH2BBMDBGBBGB3FGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBDMBBGDDDBBHBDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBMGXDXEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG8GGGDID4HDDBGGFKLGFFBHDFDENB3DGDDGFIFHHFBFBZ7QEELHDN3BGBB73
FGGDKNBBBBHHBBFH*D*MBGB***************************************************I************************************************3BBB80DGBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBBGDDDHWW3BBH8EDEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFEBBEEDDBB266
FGGDKNBDHBFBFDBBBBBBDD*TFB4DGDDGFNBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNBFFBF80DDGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDBBGGFGFIFHHFBFZ7QEELHDN3BGB7B3BB266
FGGDKNB80DDGBBBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBEEDDBB266
FGGDKNBBBBBHBFBFDB3B3BB3BBB3B33BFFF99BBB9DHHBF*4DBBGDDBFBBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHW8GBNN*MBGBIIIIIIIIIIBLBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIY5555IY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IYIY555IY555IY555IY555IIIIIY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIIY555IHDEJN26FGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBEEBFFFF99BB9DBBBBBEBMBGB555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555533*EFE4DHJEEEFEEFGDDEG*BIYHDJNDJN3MBIBIBJ*D3JNMJ*32E6FGGDKNBDBEB9DFHBFDBDDBTF4DBBI4DHDDIYDDHBDMBBBGDDDBBHBDEBDBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDXEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG8GGGDID4HDDBGGFGF3IFBBHHFFZ7QEELHDN3BGBB73BE
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNFHBBBB80DDGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBBEDDB2B66
FGGDKNBBF*LB**93BFHBHEDFJN3DDDBYFGDDDBFJBBBBGB****N*BJNJNJNJNJNJNJNJNBJNJNJNJNJNJNJNJNJNJNJNJNJNJNJNJNJNJNJNJNJNJNJNJNJN
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBBBBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
DBDDLDJNFGGDKNBB26
FGGDKNB80DDGBBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFIFHHFFZ7QBEELHDN3BGBB7B3BB266
FGGDKNBBB80DDGBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGXDEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFHHFBFZ7QEBELHDN3BGBB73B266
FGGDKNBBB80DDGBBBBBHFFDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBBEDDB266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBBBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNB80DDGBBBBBHDJND2GGD66

FGGDKNBBB33BBB3BBB3BHHBBF*HBFFDBBDGDDGFFGGDKNBGDBEHBFFBFFDBDDIYBB9DGDDFBFBBFFBB4DBBBBBBBBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHW*8GB****NN*MBNBFGBGBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
FGGDKNB80DDGBBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFHHFFBZ7QEELHDN3BGB73266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBBBBEBHFEEFEEBFFDEBEDDEEBIE80GBE262MBGB
FGGDKNB80DDGBBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGXDEEEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFBIFHHFBBFZ7QBEELHDN3BGB7B3BB266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNBBBB*GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*BBB3GDBEBHFEEFEEBFFDEBEDDEEBIE80GBE262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*B3GBBDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 1621: invalid continuation byte
FGGDKNBBFFFHBB80DDGBBBBHFFBDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFBIFBHHFBBFZ7QEELHDN3BGBB73BB266
FGGDKNB80DDGBBBFBBBHFFDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGXDEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGBFBIFHHFBBBFZ7QEELBHDN3BGB7B3266
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 2647: invalid continuation byte
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 1889: invalid continuation byte
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 2512: invalid continuation byte
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 2145: invalid continuation byte
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 647: invalid continuation byte
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNBBBB*GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB

FGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EBDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBMGXDE
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 1959: invalid continuation byte
FGGDKNBBFLB**9BFHDJN3*3HBEFDDDBJNYFGDDDBFBBBBGB*****JNJNJNJNJNJNJNJNJNJNJNJNJNJNJNBJNJNJNJNJNJNJNJNBJNJNJNJNJNJNJNJNJNJNJNFK
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBEEBBBBBEHHBMBGB555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555533*EFE4DHJEEEFEEFGDDEG*IYHDBJNDJN3MBIBIBFJ*DB3BGGDEBBBBBHHBHBBDBGBB3JNMJ*3KLFHDFENDBDGDDGFBFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBDMBBGDDDBBHBDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB55F5555B5N55BF5F55*5B5D555B5BB5B5BB5T55DDBBF45D55B5B5M5NG555555B5N5X5D5X55555H5E555E555E5555E5555B55E955*5B555E555959595E959595555E5G5****5E555E55555555E55E55E555555EEEEEEEEEMIIBEJ*DDE32E6E2EMBGBEEEEEEE
FKBBBFFGGDNBBBEBHGDDGFDBDHWFF4DBBDNBBFFHT*2*6FKFBBHBBFFGGDNBBBDF3FFD4D3
FGGDKNHBBB999BBBFFDDDBTFBDB4DE*9E9BBBBB***BBBBB**26
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 1792: invalid continuation byte
FGGDKNBBLBHDJN26FGGDKNBHHGDDBW26
FGGDKNBBB80DDGBBBBFBHFFDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEGDGGGDBID4HDDGGFGFBIFHHFBFBZ7QEBELHDEN3BGB7B3BB2B66
FGGDKNB80DDGBBBBBBHFFDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBBEDDB266
FGGDKNBBBBB3B3BE80DDGBBBBBHFFBDJNFGGD
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBEEB80GB262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNBBBBBB3BB33B333BB3B3EBFFF999DEFEEEEHBBEEEEEEHHBBF*4DBBBBGDDDEBEFBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHW8GBNN*EEEBL3HDJBJJ***D26FGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGXDEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFBIFHHFBBFZ7QEELHDN3BGB73BB26
FGGDKNBBBBB3BB33B3BB3B333EEFEEFBFEBFFF999DEFEEEEHBEEEEEEHHBBF*4DBBBBGDDDEBEFBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHW8GBNN*EEEBLHDMBGBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIY5555IY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IYIY555IY555IY555IY555IIIIIY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIIY555IIY3JBJJ***D26
FGGDKNDBBBBBHHFFBFBBFBLBHBDEJNDFHFDB4DHFGDDEJHBBGNBBIGF*IDFLDJNF2B6FGGDKNDEEBBBBFKBBBFFGGDNBBBBBFBBBBHBBDFFDFB4BHBBBBBBBBBBEHHBE26FEEFFBEBEBFHDEFGDDEEEEEEEEEEENNNN3NNNNNNNNNNNNBBBNBBNNNNNNNNN3BBBB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBBBBHFEEFEEBFFDEBEDDEEBIEEEBBBBBEHHBMBGB555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555533*EFE4DHJEEEFEEFGDDEG*BIYHDJNDJN3MBIBIBFJ*DB3BGGDEBBBBBHHBHBBDBGBB3JNMJ*3KLFHDENFDBDGDDGFFGGDKNBDBEB9DFHBFDBDDBTF4DBBI4DHDDIYDDHBDMBBBGDDDBBHBDEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGB555X5D5X5F55555NFF5E5E*555B55EDBBBE55BB5BBEB55TE555F54DE5555555N55E5BB555E55555NEHB555E555E5555555E555555B9E*5B55555E55959595959E9555E55G***5E*555555E555555E555E55555E5EEEEMIIBJ*DDB32E6E2MBGBEEEEEENBGIY8GGGD9DGDDFID4HDDBFFBB3GGFGF3IFHHFBBFZ7QEELHDN3FGGDKNBHGDDDBBBBG*DI7GBFB3FB9DBBGFD3FBFFIYNDTFH
FGGDKNBBBBHHBBFH*D*MBGB***************************************************I************************************************3BBB80DGBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFIFHHFFZ7QEBELHDN3BGB7B3BEE266
3BHHDDBGKDBBGGBBDMGBBIBXDDBBEBGH8DGGGDDNB26D2GGD6FGGDKNBBBBBB3BB33B333BB3B3FFF999DFHBBHHBF*4DBBBBGDDDBFBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHW8GBNN*MBB3LBGBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIY5IY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IYIY555IY555IY555IY555IIIIIY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIIY555IIY555HDEJ
FKBBBFFGGDNBBBEBHGDDGFBFDFD4HWDBBNDBBHFFBTID46*2*6FGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGXDEEEEEEEEEEEEEEEEEGDGGGDBID4HDDBGGFGFIFHHFBFZ7QEBELHDN3
FGGDKNBDHBFBFDBBBBBBDD*TFB4DGDDGFNBBHBBBBBBBBB3EJHIGF*IDFLDJ8Z7*3QNFKBBBFFGGDNBBBBBHBFBBBBDDBFFBHBBBFLH4BDJNFKFBHBBFFGGDNBBBBE26BB26IYBLHDEJN***3B*2B6FGGDKNBDHEEBBFEEEEEBFDEBBBBBBEEDD*ETF4DGDDEGFNBBBHBBBBBBBBBBBEBBJLBHJBJJJJJJNB***3*26
FGGDKNHB80DDGBBBBBHDJNFKBBBFFGGDNBBBHFFDB4EBDGDDGFDHWBBNDBBFFHT*2*66
FGGDKN8B0DDGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEEEEEGDGGGDBID4HDDGGFGFBIFHHFFZ7QBEELHDN3BGB73BB266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBEEBFFFF99BB9DEBB80GBE262MBGB
FGGDKNB80DDGBBBFBBHFFBDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDGGBFGFEBBBDDBB2B66
FGGDKNBBGBBFBBFBFFF999DFHBBHHBBB99BBBFDDDTFBD4DE*FBB9GB9IGDDBBFFBE980GBBBBBBBBYDFBG****FKFBBHBBFFGGDNBBBFFD3FD4D
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBBBBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNBB3BBFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEBEEEEEEE
FGGDKNBGDBEHBFFBFFDBDDIYBB9DGDDFBFBBFKBBBFFGGDNBBBEHBGDDFGBFDFD4HDWBBNBBBDHFFTID46*2*6
HWW3BBDHH8EBDKGGDEBD4DBDDHDDBBHDIBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBEBDDDBBBMGBXDEEEEEEBBEEEEEEEEEEGDGGGDNMBID4HDDDGBGBFFGFBIFBHDHFBFZ7QEBELHDN3BG4BB7B3BFGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJEJN26D2GGD62MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*BBB3GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJN2MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKN80DDGBBBBBBHFFDJNFGGDKNEB3BB3B36B3HEEBFEEFEEEEFFDEBB3B3
FGGDKNBHB80DDGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFBEBBBDDBB266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBBBBHFEEFEEBFFDEBEDDEEBIEEEBBBBBEHHBMBGB555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555533*EFE4DHJEEEFEEFGDDEG*BIYHDJNDJN3MBIBIBFJ*DB3GGDEBBBBBBHHBHBBDBGBB3JNMJ*3KLFHDBENFDBDGDDGFFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBDMBBGDDDBBHBDEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFBBNBFFB*BDBBBBBBBBBTF4DDDBBBNMBGBHXDXB9E*BEEEE99999E9EEG***E*EEEEEEEEEEEEEEEEEEEEEEEEG8GGGDID4HDDGGFGF3EB555555555555555B55555555555BB55555555555555555555B555555N555555555555555555555555555555555555555555555555MIIBJ*DDNB32E62MBGBBIY9DGDDFBFFDDBB3BB26FGGDKNBHGDDDBBB*DIGBF3BFB9DBNBGFD3FBFFIYDTFHBBBBBB*3*HFGBDG*HFBZ7Q*U*HHDBJJJFINBUHEFF9BBZ7N*9F*BB*BB9B*TBBBBB9B
5IY5555IIY555IY555IY555IY55IIY555IIY555II3LBHDEJN2GGD6FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 1960: invalid continuation byte
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNBBBBBBHEEBBFEEEEEFDEB3BB3B3BB3B33EBFFF99BBB9DEEEEEEHHBF*4DBBGDDEBEFBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHW8GBNN*EBLMBGBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIY5555IY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IYIY555IY555IY555IY555IIIIIY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IIYHDJBJJ***D2FGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE26
FGGDKN80DDGBBBBBBHFFBDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBBDDBB266
FGGDKNB80DDGBBBFBBBHFFDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDBEEEEEEEEEEEEEEEGDGGGDID4HDDGGF
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBBBBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKN8BFFBBBBB9DHHBBF*4DBBBBBBHGDDDFBBBBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN3HWNN*MBGBIIIIIIIIIIIIIIIIIBLIIIIIIIIIIIIIIIIIIIIIIIIIIIIY5IY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IYIY555IY555IY555IY555IIIIIY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIIY555II3HDEJN2B6FGGDKN8EEFEEE
FGGDKNBBBBB3BB33B3BB3B333FFBFBFFF999DFHBBHHBF*4DBBBBGDDDBFBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHW8GBNN*BMBBL3GBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIY5BIY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IYF5G5G5DIYKN5B55*IGYDB5E55IY55B5HFIEY555IY555IYIY555EIY555IY555IYF555IIIIIY555IY555IIY555IY555IY555IY555IY555IY555EIY555IY555EBFIY555IY555IIIYF5D5E5IBHDEEJN26DDEEBIEBB80GBE26
FGGDKNBHB80DDGBBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFHHFBFZ7QEBELHDN3BGBB73266
FGGDKNB80DDGBBBFBBBHFFDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EBDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFEBBBBBDDBB2B66
FGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EBDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFIFBHHFBFZ7QEELBHDN3BG7B3BE26
FGGDKNBB80DDGBBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBDDBB266
FGGDKNB80DDGBBBBBHDJN
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNBBBB*GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKN80DDGBBBBBBHFFDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGBFBEBBDDBBB2BB66
FGGDKNBB80DDGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBDDBBB266
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 1960: invalid continuation byte
3FBB9DEBBBBB3HGBFFFFDBFFF99BB9EGDB*3B33HHB8BBBBUD*K4IYDDHFGDDEJBGNBBIGF*IDFLHDJN26FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNB80DDGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFEBBEDDBBB266
EBBELHDN3BG4H8BBZ7FB
DBBDDLBBDJNFGGDKNBBB80DDGBBBBFBHFFDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGXDEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFHHFBFZ7QEELHDN3BG7B3BB266
FGGDKNBBBBBFHBHHBFFBF*IYDGDDD3FKBBBFFGGDNBBBBBHBBBBBDDFFLHDJNFF4
FGGDKNBB80DDGBBBBBHFFDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFBEBBBBEDDB266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB

FGGDKNB80DDGBBBFBBBHFFDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFHHFBFZ7QEELHDN3BGBB7B3B266
FGGDKN80DDGBBBBHBDJN6FGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBMGXDEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDD
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 1958: invalid continuation byte
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 2960: invalid continuation byte
FGGDKNB80DDGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEEGDGGGDID4HDDBBGGFGFEBBBEDDBB266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNBBBBB3BB33B3BB3B333FFFFFF999DFHBBHHBF*4DBBBBGDDDBFBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHW8GBNN*MBGBBIIIIIIIIIIIII
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBBBBHFEEFEEBFFDEBEDDEEBIEEEBFFFF999DEBBBBBEBMBGB555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555533*EFE4DHJEEEFEEFGDDEG*IYHDBJNDJN3MBIBIBJ*DB3BBEBBBBBGGDHBBDBGB3JNMJ*B32E62BMBGBKLBFFDBDHDEGDDGFNBFNFF*BDBBBBBBTF4DNBHB9*BF9G9G9D99K9NBDBEG****B9DFHBFDBDDBTF4DBBI4DHDDIYDDHBDMBBBGDDDBBHBDEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGXDXEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEENBEG8GGGDID4HDDBBGGFGF3IFBBBHHFBFZ7QENNBIYBB9DGDDELHDN3FBFFBB3BGB7BB3FGGDKNBHGDDDBBB*DIGBFBF3B9DBBGFED3FBFFEIYDTFHBBBBBB**
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNBBBB*GDBEBHFEEFEEBFFDEBEDDEEBIEEEEEB80GB262MBGB

DDBBEEEBGGDGH8DGGGDDNXB2B6D6FGGDKN80DDGBBBBHDJNFKNBBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBHEBDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEDDID4HDDBGGFGFIFHHFBFZ7QBEEBLHDN3BG73BB6
FGGDKNFHBBBB80DDGBBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGXDEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFBIFHHFBBBFZ7QEEBLHDN3BGB7B3EEEE266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNBBBBFFBFHBHHF*D*MBGB***************************************************I************************************************3BBB80DGBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBMGBXDEEEEEEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFBGFEBBEEDDB2B66
FGGDKNBBBBB33BBBE3B3BB3B333FFFBFFF999DFBHBBHHBF*4DBBBBGDDDBFBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHW8GBNN*MBGBIIIIIIIIIIII3BIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIY5IY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IYIY555IY555IY555IY555IIIIIY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IILHDEJN26
DBDDLBDJNFGGDKNB80DDGBBBBBBHFFDJNBBBBFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDGBBGFGFIFBHHFFZ7QEELHDN3BGBB7B3BE266
FGGDKNB80DDGBBBBBHBDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBMGBXDEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBBEDDB266
FKBBBFFGGDNBBBBHBBBBBDDFFFF34LHDJNFKBBBFFGGDNBBBEHBFBGDDGFDFD4BHWDBBBNDBBHFFT*2*6LBDJN
FGGDKNB80DDGBBBBBFBHFFBDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFIFHHFBBFZ7QBEELHDN3BG7B3B266
FGGDKNBBB3BBB3BBB3B3FFBFBFFF999DFHBBHHBF*BFDBDGDDGF

FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBBBBHFEEFEEBFFDEBEDDEEBIEEEEEB80GB262MBGB
FKBBBFFFGGDNBBBBBHBBBBBDDFFBF4LHDJNFKBBBFFGGDNEBHBGDDGFBFD4DFDBHWNBBDHFFBT*2*6LBDJN
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNBB80DDGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBDDBBB266
FGGDKNBBB3BBB3BBB3B3FFBFBFFF999DFHBBHHF*BFDDGDDGF
D2GGD6FGGDKNBDHBFFDBBBBBBBDD*TFB4DGDDGFNBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
FGGDKNHBBBB999BBBBFFDDDTFBD4DE*F9EB9GB9DIGDDBBFFB***BB*EFHHHZ7QFB8FBBBBBBB99DBBBBYDFBGB*****F9999F**GFIGGGTTE*E*****BI*F*FDBNF****E*B***BBG**U**B*BBBBBBB**TIYHEJN*IDLHDHJNJNJNJNJNJNJNJNJNJNJNJNJNJNJNFGGDKNBNNTBBB9HBFBFDNGDD*B26
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBBBBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNB80DDGBBBBBHBDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBBEDDB266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBBBBEBHFEEFEEBFFDEBEDDEEBIEEB80GB262MBGB
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 6034: invalid continuation byte
FKBBBFFGGDNBHFEBBFDGDDGF4DDBHWNDBBFFBHBT*2*6FKFBBHBBFFGGDNBBBDFFFD34D26
FGGDKNBBBBHHBBFH*D*MBGB***************************************************I*************************************************3BBB80DGBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFHHFFZ7QEBELHDN3BGBB7B3BEE266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*BBB3GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKN*FBHFHFBFGDDBGDBBIB3F8BB3FFDFGGDKNBDBEB9DFHBFDBDDBTF4DBBI4DHDDIYDDHBDMBBBGDDDBBH8EBDEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGXDXXXEEEEEEEEEEEEEEEEEEEEEEEEEGGGGDID4HDDGGFGF3BIFHHFBFZ7QEELHDN3BG7B3
FGGDKNHB80DDGBBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBBDDBBB266
DIHDDIYDDHBNDMBBDGHGDDDBBHWW3BBDH8EDKBGDEB4DBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBEBDDBBBBMGXDEEEEEEBBEEEEEEEEEEEGDGGGDBID4HDDDGGFFGFIFHDHFBBBFBZ7QEBELHDN3BG47FGGDKNB380DDGBBBBBBHDJN26D6FGGDKN8BB6BFBFB9DFH
FGGDKNB80DDGBBBBBBHDJNFGGDKNBBDBBBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EBDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBBBDDBB266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBBBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 1891: invalid continuation byte
B33BBB3B3HHDBBBFFF99BB9D8DGBBBBGGBKBBEFBUHTFD4D*IYDHFBGDDEJGNBBIGF*IDFLHDJN26FKBBBFFGGDNBBBBBHBBBBBDDLFHFFFDJN34FKBBBFFGGDNBBBEBHFFDB4GDDDBBGFDHWBNBDBBFFHBT*2*6LBDJNFGGDKN8BFFHBFBB
DBBDDLBBDJNFGGDKNBBBBHHBFH*D*MBGB***************************************************I*************************************************3BBB80DGBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFBIFHHFBFBZ7QEEBLHDN3BGBB7B3BEEE266
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*BBB3GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNB80DDGBBBBFBBHFFDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EBDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBBDDB266
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 1958: invalid continuation byte
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 3777: invalid continuation byte
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 1793: invalid continuation byte
FGGDKNBBGBBD6FBBFBFFF999DFHBBHHBBB99BBBFDDDTFBD4DE*FBB9GB9IGDDBBFFBE9B80GBBBBBBBBYDFBG****
FGGDKNBB80DDGBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFIFHHFBFZ7QEBELHDN3BGBB7B3BEEEE266
FGGDKNB80DDGBBBBBHDJNFGGDKN8BFFBBBBB9DHHBBFB*4DBBBBBBH6GDDDFBBBBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN3HWNN*MBB3LHDEGBIIIIIIIIIII
FGGDKNB80DDGBBBBFBBHFFBDJNFGGDKNBBDBBBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EBDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBBDDBB266
FGGDKN80DDGBBBBBBHFFDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGXDEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFIFBHHFBFZ7QBEELHDN3BGB73BE266
FGGDKNBB80DDGBBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBBMGBXDEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBBDDBB2B66
FGGDKNBBBBHHBFH*D*MBGB***************************************************I************************************************3BBB80DGBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFBBBIFHHFBFBZ7QEELHDN3BGBB73BEEE266
FGGDKNB26
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 1958: invalid continuation byte
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBEEB80GB262MBGB
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 1149: invalid continuation byte
FGGDKNHB80DDGBBBBBBHFFDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EBDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGXDBEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDBGGFGFIFBHHFBBFBZ7QEELHDN3BGBB73BB266
FGGDKNBBBBB33BBBE3B3BB3B333FFBFBFFF999DFHBBHHBF*4DBBBBGDDDBFBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHW8GBNN*MBGBIIIIIIIIIIIIBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIY5BIY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IYIY555IY555IY555IY555IIIIIY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIIY555IY555ILHDEJN26FGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBEE26
FGGDKNBBBBB3B33B3BB3B3EFFF999DEFEEEEHBEEEEEEHHBBF*4DBBBBGDDDEBEFBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHW8GBNN*EEEBL3MBGBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFGGIDY5K5N5B5I*YGD5B5E5IY555IBHIFY5E55IY555IY555IIIIY555EIY555IY555IY555IY5F55IY555IY555IY555IY555IY555IY555IY555IIY555IY5E55IY555IY555IEY555IY555IY555IY555IY555IY555IY555IY555IYIBY55F5IY555IY555IY555IIIIIY555IY555IIY55F5DIEY555IY555IY555IY555BIYE555IY555IY555IY555DDEEIY555BIIEIIYB555IIBY80GBHDEJBJJ***D2626
FGGDKN8FHBBFFBB9DBBBFB*4DBBBBBBBGDDDFBBBBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN3HWNN*MBGBIIBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIY5IY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IYIY555IY555IY555IY555IIIIIY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555I3LHDEJN2B6FGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBEEBFFFF99BB9DEBB80GBE26
FGGDKNBBGBBBBFFF999DBHHBHBBB99BBBFFDDDTFBD4DE*FBB9GBB9IGDDBBFFBE9F***TTTT99999999TTT*******N*3FBBBF8BBHZ7Q*EBFBBBBB99DIYGYDBG****9*F9999F**GFIGGBTTBFGGDKNBDBEB9DFHBFDBDDBTF4DBBI4DHDDIYDDHBDMBBBGDDDBBHB8EBDEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDXXXXXXXXXXEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEGGGGDBID4HDDGGFGF3EBBBBEEEEDDBB26
FGGDKNBBBBHHBFH*D*MBGB***************************************************I***************************************************3BBB80DGBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGXDEEEEEEEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFEBBEEDD
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBBBBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*BBB3GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
FGGDKNBBBBBFFBHBBFFBFD80DGBBBBHDJNFGGDKNBBBBB3BB33B333BB3B3BFFF999DFHBBHHBF*4DBBBBGDDDBFBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHW8GBNN*MBGBB3LBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIY5IY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IYIY555IY555IY555IY555IIIIIY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IIHDEJN26
FGGDKNBB80DDGBBBBBHDJNFGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDBEBDBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFHHFBFZ7QEBELHDN3BGB73B266
FGGDKN*BBBBDBHBBBBFB*LHDJN3**9BE3EB3FFJNDDB*JNJNJNJNJNJNJNJNJNJNJNJNJNJNJNBJNJNJNJNJNJNJNJNBJNJNJNJNJNJN
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEBB80GBE262MBGB
FKFBBHBBFFGGDNBBBDF3F3FD4DFGGDKN80DDGBBBBHDJN
FGGDKNBBBBBB3BB33B333BB3B3BFFF999DFHBBHHBF*4DBBBBGDDDBFBNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHW8GBNN*MBGBIIBIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIY5BIY555IY555IIY555IY555IY555IIIIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IYIY555IY555IY555IY555IIIIIY555IY555IIY555IY555IY555IY555IY555IY555IY555IY555IY555IY555IIIY555ILHDEJN26FGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGBFIFHHFBBFZ7QEELHDN3BG7B3B26
FGGDKNB80DDGBBBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFBEBBBDDBBB2B66
FGGDKNBGDBEHBFFBFFDBDDBLBHDEBJJJNFGGDKNB*GDBEBHFEEFEEBFFDEBEDDEEBIEB80GBE262MBGB
Traceback (most recent call last):
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 205, in <module>
    main(sys.argv[1:])
  File "/Users/samoshet/Documents/SJSU/Project/seq-gen/scripts/seq-gen.py", line 164, in main
    Lines = file1.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 1793: invalid continuation byte
FGGDKNBBBBBFFBHBBFFBFD80DGBBBBHDJNFGGDKNBDBEBBBB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGBXDEEEEEEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFBHHFBFZ7QEELHDN3BGBB73BB26NBBBBBBBBBBBBBBBBBBBBBBBBBB
FGGDKNBBBBDBEB9DFHBFDBDDTF4DI4DHDDIYDDHBNDMBBGDDDHWW3BBH8EDEBDBBBHBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDBBBMGXDEEEEEEEEEEEEEEEEGDGGGDID4HDDGGFGFIFHHFFZ7QEBELHDN3BGBB73BBE26NI4DHDDDDHNDMBDDDHBBBBBBBBBBBBBDBBMBXDEDDBNBBBB
